// UK Market Prices - Auto-generated by uk_price_scraper_v3.py
// Last updated: 2026-01-22 13:02
// Sources: JJ Fox (search), CGars Ltd (PDF)

export const ukMarketPrices = {
  "Montecristo": {
    "Brilllantes": {
      "boxPrice": 150.0,
      "boxSize": 18,
      "perCigar": 8.33,
      "sources": [
        "jjfox"
      ]
    },
    "Leyendas": {
      "boxPrice": 150.0,
      "boxSize": 20,
      "perCigar": 7.5,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Trinidad": {
    "Robusto Extra": {
      "boxPrice": 150.0,
      "boxSize": 12,
      "perCigar": 12.5,
      "sources": [
        "jjfox"
      ]
    },
    "Esmerelda": {
      "boxPrice": 150.0,
      "boxSize": 12,
      "perCigar": 12.5,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Hoyo de Monterrey": {
    "Destinos": {
      "boxPrice": 150.0,
      "boxSize": 20,
      "perCigar": 7.5,
      "sources": [
        "jjfox"
      ]
    },
    "Double Corona": {
      "boxPrice": 150.0,
      "boxSize": 50,
      "perCigar": 3.0,
      "sources": [
        "jjfox"
      ]
    },
    "Petit Robustos": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Ramon Allones": {
    "Absolutos": {
      "boxPrice": 150.0,
      "boxSize": 20,
      "perCigar": 7.5,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Bolivar": {
    "New Gold Medal": {
      "boxPrice": 150.0,
      "boxSize": 10,
      "perCigar": 15.0,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Partagas": {
    "Lusitinas": {
      "boxPrice": 150.0,
      "boxSize": 10,
      "perCigar": 15.0,
      "sources": [
        "jjfox"
      ]
    },
    "Linea Maestra Maestros": {
      "boxPrice": 150.0,
      "boxSize": 20,
      "perCigar": 7.5,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Cohiba": {
    "Vistosos": {
      "boxPrice": 150.0,
      "boxSize": 10,
      "perCigar": 15.0,
      "sources": [
        "jjfox"
      ]
    },
    "Siglo VI": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    },
    "Maduro 5 Genios": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    },
    "Maduro 5 Magicos": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    },
    "Behike 52": {
      "boxPrice": 150.0,
      "boxSize": 10,
      "perCigar": 15.0,
      "sources": [
        "jjfox"
      ]
    },
    "Siglo I": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    },
    "Medio Siglo": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    },
    "Behike 56": {
      "boxPrice": 150.0,
      "boxSize": 10,
      "perCigar": 15.0,
      "sources": [
        "jjfox"
      ]
    },
    "Lanceros": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Name": {
    "Quantity Purchased (Boxes)": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Topes": {
    "1": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Vistosos": {
    "1": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Robusto Extra": {
    "1": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    }
  },
  "Linea Maestra Origen": {
    "1": {
      "boxPrice": 150.0,
      "boxSize": 25,
      "perCigar": 6.0,
      "sources": [
        "jjfox"
      ]
    }
  }
};

export const priceMetadata = {
  lastUpdated: "2026-01-22",
  sources: ["JJ Fox", "CGars Ltd"],
  currency: "GBP",
  note: "Prices fetched from inventory in Google Sheet"
};
